# Generated by Django 5.1.4 on 2024-12-17 09:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Agra', 'Agra'), ('Aligarh', 'Aligarh'), ('Allahabad (Prayagraj)', 'Allahabad (Prayagraj)'), ('Ambedkar Nagar', 'Ambedkar Nagar'), ('Amethi', 'Amethi'), ('Amroha', 'Amroha'), ('Auraiya', 'Auraiya'), ('Azamgarh', 'Azamgarh'), ('Badaun', 'Badaun'), ('Baghpat', 'Baghpat'), ('Bahraich', 'Bahraich'), ('Ballia', 'Ballia'), ('Balrampur', 'Balrampur'), ('Banda', 'Banda'), ('Barabanki', 'Barabanki'), ('Bareilly', 'Bareilly'), ('Basti', 'Basti'), ('Bhadohi (Sant Ravidas Nagar)', 'Bhadohi (Sant Ravidas Nagar)'), ('Bijnor', 'Bijnor'), ('Bulandshahr', 'Bulandshahr'), ('Chandauli', 'Chandauli'), ('Chitrakoot', 'Chitrakoot'), ('Deoria', 'Deoria'), ('Etah', 'Etah'), ('Etawah', 'Etawah'), ('Faizabad (Ayodhya)', 'Faizabad (Ayodhya)'), ('Farrukhabad', 'Farrukhabad'), ('Fatehpur', 'Fatehpur'), ('Firozabad', 'Firozabad'), ('Gautam Buddha Nagar (Noida)', 'Gautam Buddha Nagar (Noida)'), ('Ghaziabad', 'Ghaziabad'), ('Ghazipur', 'Ghazipur'), ('Gonda', 'Gonda'), ('Gorakhpur', 'Gorakhpur'), ('Hamirpur', 'Hamirpur'), ('Hapur', 'Hapur'), ('Hardoi', 'Hardoi'), ('Hathras', 'Hathras'), ('Jalaun', 'Jalaun'), ('Jaunpur', 'Jaunpur'), ('Jhansi', 'Jhansi'), ('Kannauj', 'Kannauj'), ('Kanpur', 'Kanpur'), ('Kasganj', 'Kasganj'), ('Kaushambi', 'Kaushambi'), ('Kushinagar', 'Kushinagar'), ('Lakhimpur Kheri', 'Lakhimpur Kheri'), ('Lalitpur', 'Lalitpur'), ('Lucknow', 'Lucknow'), ('Maharajganj', 'Maharajganj'), ('Mahoba', 'Mahoba'), ('Mainpuri', 'Mainpuri'), ('Mathura', 'Mathura'), ('Mau', 'Mau'), ('Meerut', 'Meerut'), ('Mirzapur', 'Mirzapur'), ('Moradabad', 'Moradabad'), ('Muzaffarnagar', 'Muzaffarnagar'), ('Pilibhit', 'Pilibhit'), ('Pratapgarh', 'Pratapgarh'), ('Raebareli', 'Raebareli'), ('Rampur', 'Rampur'), ('Saharanpur', 'Saharanpur'), ('Sambhal', 'Sambhal'), ('Sant Kabir Nagar', 'Sant Kabir Nagar'), ('Shahjahanpur', 'Shahjahanpur'), ('Shamli', 'Shamli'), ('Shravasti', 'Shravasti'), ('Siddharthnagar', 'Siddharthnagar'), ('Sitapur', 'Sitapur'), ('Sonbhadra', 'Sonbhadra'), ('Sultanpur', 'Sultanpur'), ('Unnao', 'Unnao'), ('Varanasi', 'Varanasi')], max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_pincode', message='Pincode must be 6 digits.', regex='^\\d{6}$')])),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact_number', message='Contact number must be 10 digits.', regex='^\\d{10}$')])),
                ('experience', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('job_description', models.TextField(max_length=240)),
                ('photo', models.ImageField(blank=True, default='photos/Untitled.jpg', null=True, upload_to='photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
